apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: pipeline11
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Shivaji1487/gitops-pipeline11.git
    targetRevision: main
    path: helm

  destination:
    server: https://kubernetes.default.svc
    namespace: bank-production-v11

  syncPolicy:
    automated:
      prune: true
      selfHeal: true